### ISSUE TITLE
Can't connect to a call due to timeout 

### ISSUE THREAD

**Issue by halcyonashes** [sinch/app-app-calling-android#25]
Here is a log of the issue(I've removed the ids for the request):
D/HttpClient: Dispatching request
D/HttpClient: Adding request
D/PubNubListener: Cancelling subscription request
D/HttpClient: Scheduling request: {id=’’, url='https://clientapi.sinch.com/V1/Session', method='PUT', headers={Accept=text/json, Content-Type=application/json; charset=utf-8}}
D/Call: onSessionTerminated: ‘’: SessionDetails [startTime=1585721064, endTime=1585721077, progressTime=0, establishTime=0, duration=0, terminationCause=TIMEOUT, error=null]
D/DefaultPeerConnectionClient: Setting  AudioManager mode to MODE_NORMAL
D/CallScreenActivity: Call ended. Reason: TIMEOUT
D/CallScreenActivity: Call ended. Reason: SessionDetails [startTime=1585721064, endTime=1585721077, progressTime=0, establishTime=0, duration=0, terminationCause=TIMEOUT, error=null]
D/DefaultPeerConnectionClient: Closing peer connection. mIsClosing = true, this = com.sinch.android.rtc.internal.client.calling.PeerConnection.DefaultPeerConnectionClient@ab4ea67
D/DefaultPeerConnectionClient: Closing audio source.
D/DefaultPeerConnectionClient: Audio source closed.
D/DefaultPeerConnectionClient: Stopping capture.
D/DefaultPeerConnectionClient: Closing video source.
D/DefaultPeerConnectionClient: Closing texture helper.
D/DefaultPeerConnectionClient: Closing PeerConnectionFactory.
D/HttpClient: Request ‘’ completed with exception: java.net.UnknownHostException: Unable to resolve host "rebtelsdk.pubnub.com": No address associated with hostname
D/HttpClient: Adding request to failed
D/HttpClient: Scheduling request for retry (delay=3000)
V/FA: Activity paused, time: 2153225897
D/DefaultPeerConnectionClient: PeerConnectionFactory closed.
D/DefaultPeerConnectionClient: PeerConnectionClient closed.
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 4
D/HttpClient: Request ‘’ completed with HTTP status 200
D/DefaultHttpService: Http response from: PUT  https://clientapi.sinch.com/V1/Session. Status: null. Content-type: text/json; charset=utf-8, body: {"Result":200,"Message":"SessionEnded"}

**Comment by masheransari** [comment]
Hi, 
Is there any solution for this TIMEOUT problem, because I am also getting this issue.
the user are unable to place a call in **onCallEnded** shows **TIMEOUT** Cause in this override method.
Looking forward to your reply.

**Comment by harshmittal2810** [comment]
I am also getting this error when the app is log in with two different login details one per time, and trying to call first or second person. It works when I uninstall the app and install and log in.
